namespace Projeli.ProjectService.Domain.Models;
public enum ProjectCategory : byte
{
    None = 0,
    Adventure = 1,
    Animation = 2,
    Art = 3,
    Business = 4,
    Cooking = 5,
    Crafts = 6,
    Design = 7,
    DIY = 8,
    Education = 9,
    Electronics = 10,
    Environment = 11,
    Fashion = 12,
    Film = 13,
    Finance = 14,
    Gaming = 15,
    Health = 16,
    History = 17,
    Hobbies = 18,
    Journalism = 19,
    Languages = 20,
    Literature = 21,
    Music = 22,
    Nature = 23,
    Photography = 24,
    Programming = 25,
    Psychology = 26,
    Robotics = 27,
    Science = 28,
    Space = 29,
    Sports = 30,
    Technology = 31,
    Travel = 32,
    Tutorials = 33,
    WebDevelopment = 34,
    Wellness = 35,
    Writing = 36,
    Other = 37
}